version: '3'

services:
  db:
    image: postgres:13
    container_name: photo-gallery-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: photo-gallery-backend
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      MEDIA_ROOT: /app/media
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: photo-gallery-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always

volumes:
  postgres_data:
  media_data:
